/* Single source of truth for the page content. Imported by the browser (app.js)
   and by the API (lib/entries.js), so task ids are defined in exactly one place. */
export const DRIVE = {
  main: 'https://drive.google.com/drive/folders/1OcXMnrUro9oyx6yzTYbI8IJI_5hi-3tU?usp=drive_link',
  photos: 'https://drive.google.com/drive/folders/1bUMlcAGaIFqmwoeUFk9Mr9yFDS4qAj2_',
  notebook: 'https://drive.google.com/file/d/1Vekadqtl2x97YMi9j4dpKB2j1U2wv-Wn/view?usp=drive_link',
  example: 'https://docs.google.com/document/d/17YYdFcZJLCrW-xZGB6M4cMswBvUwc2cmHjuXkpt19CQ/edit?usp=drive_link',
  mustadd: 'https://docs.google.com/document/d/1Ht8xv0NUfvfeU5yM3JK82MqzMBWdN9Bm0nB6nLuy6As/edit'
};
export const LINK_ORDER = ['main', 'photos', 'notebook', 'example', 'mustadd'];
export const LANG_NAMES = { he: 'עברית', de: 'Deutsch', en: 'English' };

export const SUGGESTED = 3;
export const UI = {
  he: {
    title: 'ספר המתכונים של סבתא נורית - קלרי',
    purpose: 'המתכונים של סבתא הם חלק ממי שאנחנו. בספר הזה נשמור אותם, יחד עם הסיפורים והזיכרונות שלנו, כמורשת משפחתית שתעבור הלאה לדורות הבאים. ומעל הכל, נעניק לסבתא מתנה שתמלא אותה שמחה וגאווה.',
    intro: 'בטבלת המשימות רושמים ליד המשימה את השם, את החלק שלוקחים ואת המצב שלו, כדי שכולם יראו מי עושה מה. בכל משימה יש מקום בערך לשלושה אנשים. הכי חשוב זה שביחד נמלא את כל המשימות. שימו לב שיש משימות שכולם צריכים לעשות.',
    progress: '{a} מתוך {b} משימות כבר בידיים טובות',
    langLabel: 'שפה',
    driveTitle: 'הכל במקום אחד',
    driveSub: 'תיקיית הדרייב פתוחה לכל המשפחה. את כל הקבצים, התמונות והטקסטים מעלים לשם.',
    link_main: 'תיקיית הספר', link_photos: 'תיקיית התמונות', link_notebook: 'המחברת הסרוקה',
    link_example: 'דוגמה לפורמט', link_mustadd: 'מתכונים שחייבים להיכנס',
    badge_noheb: 'בלי עברית', badge_all: 'לכולם',
    take: 'אני בפנים',
    nobody: 'עדיין פנוי',
    crowded: 'כבר יש כאן שלושה. אולי משימה אחרת צריכה אותך יותר?',
    slots: n => n === 1 ? 'יש מקום לעוד אחד' : 'יש מקום לעוד ' + n,
    nameLabel: 'השם שלך', partLabel: 'איזה חלק לוקחים?',
    add: 'להוסיף את השם שלי', cancel: 'ביטול',
    remove: 'הסרה', removeQ: 'להסיר?', yes: 'כן', no: 'לא',
    saving: 'שומר...',
    error: 'משהו השתבש בשמירה. אפשר לנסות שוב בעוד רגע.',
    rate: 'היו הרבה שמירות ברצף. כדאי לחכות רגע ולנסות שוב.',
    colTask: 'המשימה', colTip: 'איך מחלקים ונהנים', colWho: 'מי, איזה חלק ומה המצב',
    statusLabel: 'מצב', st_todo: 'עדיין לא התחיל', st_doing: 'בעבודה', st_done: 'סיים',
    filterLabel: 'סינון משימות', f_all: 'הכל', f_open: 'פנויות', f_noheb: 'בלי עברית', f_everyone: 'לכולם', f_mine: 'שלי',
    emptyFilter: 'אין משימות שמתאימות לסינון הזה.',
    loading: 'טוען את הטבלה...',
    loadError: 'לא הצלחנו לטעון את הטבלה. כדאי לבדוק את החיבור ולנסות שוב.',
    gone: 'הרישום הזה כבר לא קיים. הטבלה עודכנה.',
    tableTitle: 'טבלת המשימות',
    tableSub: 'מוצאים משימה, מוסיפים את עצמכם, ומעדכנים את המצב כשמתקדמים. הטבלה מתעדכנת אצל כולם.',
    statsLabel: 'איפה אנחנו עומדים',
    retry: 'לנסות שוב', dismiss: 'סגירה'
  },
  de: {
    title: 'Das Kochbuch von Oma Nurit - Klari',
    purpose: 'Omas Rezepte sind ein Stück von uns allen. Mit diesem Buch bewahren wir sie, zusammen mit ihren Geschichten und unseren Erinnerungen, als Familienerbe für die Generationen nach uns. Und vor allem wollen wir Oma etwas schenken, das sie mit Freude und Stolz erfüllt.',
    intro: 'In der Aufgabentabelle trägst du neben einer Aufgabe deinen Namen ein, dazu deinen Teil und wie weit du bist. So sehen alle, wer sich um was kümmert. Pro Aufgabe ist Platz für etwa drei Leute. Das Wichtigste ist, dass wir gemeinsam alle Aufgaben abdecken. Und schau mal: Ein paar Aufgaben sind für alle gedacht.',
    progress: '{a} von {b} Aufgaben sind schon in guten Händen',
    langLabel: 'Sprache',
    driveTitle: 'Alles an einem Ort',
    driveSub: 'Der Drive-Ordner ist für die ganze Familie freigegeben. Dort kommen alle Dateien, Fotos und Texte hinein.',
    link_main: 'Buch-Ordner', link_photos: 'Fotoordner', link_notebook: 'Omas Heft (Scan)',
    link_example: 'So sieht ein Rezept aus', link_mustadd: 'Rezepte, die unbedingt rein müssen',
    badge_noheb: 'Ohne Hebräisch', badge_all: 'Für alle',
    take: 'Ich mache mit',
    nobody: 'Noch frei',
    crowded: 'Hier sind schon drei dabei. Vielleicht braucht dich eine andere Aufgabe mehr?',
    slots: n => n === 1 ? 'Platz für 1 weitere Person' : 'Platz für ' + n + ' weitere',
    nameLabel: 'Dein Name', partLabel: 'Welchen Teil übernimmst du?',
    add: 'Namen eintragen', cancel: 'Abbrechen',
    remove: 'Entfernen', removeQ: 'Entfernen?', yes: 'Ja', no: 'Nein',
    saving: 'Wird gespeichert...',
    error: 'Das Speichern hat nicht geklappt. Versuch es gleich noch einmal.',
    rate: 'Gerade wurde sehr oft hintereinander gespeichert. Warte kurz und versuch es dann noch einmal.',
    colTask: 'Aufgabe', colTip: 'Aufteilen und Spaß haben', colWho: 'Wer, welcher Teil, wie weit',
    statusLabel: 'Stand', st_todo: 'Noch nicht begonnen', st_doing: 'In Arbeit', st_done: 'Fertig',
    filterLabel: 'Aufgaben filtern', f_all: 'Alle', f_open: 'Noch frei', f_noheb: 'Ohne Hebräisch', f_everyone: 'Für alle', f_mine: 'Meine',
    emptyFilter: 'Keine Aufgabe passt zu diesem Filter.',
    loading: 'Tabelle wird geladen...',
    loadError: 'Die Tabelle konnte nicht geladen werden. Prüf kurz deine Verbindung und versuch es noch einmal.',
    gone: 'Dieser Eintrag existiert nicht mehr. Die Tabelle wurde aktualisiert.',
    tableTitle: 'Die Aufgabentabelle',
    tableSub: 'Aufgabe finden, dich eintragen und den Stand aktualisieren, wenn es vorangeht. Alle sehen die Änderungen.',
    statsLabel: 'Wo wir gerade stehen',
    retry: 'Nochmal versuchen', dismiss: 'Schließen'
  },
  en: {
    title: 'The Cookbook of Grandma Nurit - Klari',
    purpose: "Grandma's recipes are part of who we are. With this book we're keeping them safe, together with her stories and our memories, as a family legacy to pass on to the generations after us. Above all, we want to give Grandma something that fills her with joy and pride.",
    intro: "In the task table, add your name next to a task, along with the part you're taking on and how far along you are, so everyone can see who's doing what. Each task has room for about three people. What matters most is that together we cover every task. And note that a few tasks are for everyone.",
    progress: '{a} of {b} tasks are already in good hands',
    langLabel: 'Language',
    driveTitle: 'Everything in one place',
    driveSub: 'The Drive folder is shared with the whole family. Put all files, photos and texts there.',
    link_main: 'Book folder', link_photos: 'Photos folder', link_notebook: 'Scanned notebook',
    link_example: 'What a recipe should look like', link_mustadd: 'Must-have recipes',
    badge_noheb: 'No Hebrew needed', badge_all: 'For everyone',
    take: 'Count me in',
    nobody: 'Still open',
    crowded: 'Three people are already on this one. Another task might need you more.',
    slots: n => n === 1 ? 'Room for 1 more' : 'Room for ' + n + ' more',
    nameLabel: 'Your name', partLabel: 'Which part are you taking on?',
    add: 'Add my name', cancel: 'Cancel',
    remove: 'Remove', removeQ: 'Remove?', yes: 'Yes', no: 'No',
    saving: 'Saving...',
    error: "That didn't save. Please try again in a moment.",
    rate: 'Lots of saves in a row. Give it a moment, then try again.',
    colTask: 'Task', colTip: 'How to split it and have fun', colWho: 'Who, which part, status',
    statusLabel: 'Status', st_todo: 'Not started', st_doing: 'In progress', st_done: 'Done',
    filterLabel: 'Filter tasks', f_all: 'All', f_open: 'Still open', f_noheb: 'No Hebrew', f_everyone: 'For everyone', f_mine: 'Mine',
    emptyFilter: 'No tasks match this filter.',
    loading: 'Loading the table...',
    loadError: "Couldn't load the table. Check your connection and try again.",
    gone: 'That entry no longer exists. The table has been refreshed.',
    tableTitle: 'The task table',
    tableSub: "Find a task, add yourself, and update your status as you go. Everyone sees the changes.",
    statsLabel: 'Where we stand',
    retry: 'Try again', dismiss: 'Dismiss'
  }
};

export const PARTS = [
  {
    num: 1,
    t: { he: 'תמונות ועיצוב', de: 'Fotos und Gestaltung', en: 'Photos and design' },
    sub: {
      he: 'המשימות האלה לא דורשות עברית בכלל, ולכן הן מתאימות במיוחד למשפחה בזלצבורג ולכל מי שנוח לו יותר בלי טקסט בעברית.',
      de: 'Für diese Aufgaben braucht man kein Wort Hebräisch. Sie passen also wunderbar für euch in Salzburg und für alle, die lieber ohne hebräische Texte arbeiten.',
      en: "No Hebrew needed for any of these, so they're a lovely fit for the Salzburg family and anyone who'd rather not work with Hebrew text."
    },
    tasks: [
      { id: 'archive', badge: 'noheb', links: ['photos'],
        t: { he: 'ארכיון משפחתי', de: 'Familienarchiv', en: 'Family archive' },
        d: { he: 'מדפדפים באלבומים הישנים, סורקים תמונות של סבתא מהילדות ושל המשפחה לאורך השנים, ומעלים אותן באיכות גבוהה לתיקיית התמונות.',
             de: 'In alten Fotoalben stöbern, Kinderbilder von Oma und Familienfotos aus all den Jahren einscannen und in guter Qualität in den Fotoordner hochladen.',
             en: "Leaf through old albums, scan Grandma's childhood photos and family pictures from over the years, and upload them in good quality to the Photos folder." },
        ex: { he: 'למשל: האלבומים בבית של ההורים', de: 'z. B. die Alben bei meinen Eltern', en: "e.g. the albums at my parents' place" },
        tip: { he: "מחלקים לפי בתים או עשורים, וסורקים ביחד עם כוס קפה ואלבום פתוח - כל תמונה מביאה איתה סיפור.", de: "Nach Haushalten oder Jahrzehnten aufteilen und gemeinsam bei einem Kaffee scannen - zu jedem Foto gibt es eine Geschichte.", en: "Split by household or by decade, and scan together over coffee - every photo comes with a story." } },
      { id: 'paparazzi', badge: 'noheb', links: ['photos'],
        t: { he: 'פפראצי אוכל', de: 'Food-Paparazzi', en: 'Food paparazzi' },
        d: { he: 'מצלמים את המנות שסבתא מכינה בימים אלה, או מחפשים בטלפון תמונות מארוחות חג ומביקורים מרטינגן ומזלצבורג.',
             de: 'Omas Gerichte fotografieren, wenn sie gerade kocht, oder im Handy nach Bildern von Festessen und Besuchen aus Ratingen und Salzburg suchen.',
             en: 'Snap the dishes Grandma is cooking these days, or look through your phone for pictures from holiday meals and visits from Ratingen and Salzburg.' },
        ex: { he: 'למשל: תמונות מארוחות החג', de: 'z. B. Bilder von Festessen', en: 'e.g. photos from holiday meals' },
        tip: { he: "כל אחד אחראי על ביקור או חג אחד, ומצלמים את סבתא בפעולה, לא רק את הצלחת.", de: "Jede Person übernimmt einen Besuch oder ein Fest - und fotografiert Oma beim Kochen, nicht nur den Teller.", en: "Each person covers one visit or holiday, and catches Grandma in action, not just the plate." } },
      { id: 'editing', badge: 'noheb', links: ['photos'],
        t: { he: 'עריכת תמונות', de: 'Bildbearbeitung', en: 'Photo editing' },
        d: { he: 'חיתוך ושיפור של תמונות (כלי AI יכולים לעזור מאוד עם תמונות ישנות), והכנת קולאז\'ים לעמודי המעבר בספר.',
             de: 'Fotos zuschneiden und aufhübschen (bei alten Bildern helfen KI-Tools oft erstaunlich gut) und Collagen für die Zwischenseiten gestalten.',
             en: "Crop and touch up photos (AI tools work wonders on old pictures) and put together collages for the book's divider pages." },
        ex: { he: 'למשל: הקולאז\'ים', de: 'z. B. die Collagen', en: 'e.g. the collages' },
        tip: { he: "אחד משחזר תמונות ישנות, אחר מרכיב קולאז'ים, ואפשר לערוך יחד בשיחת וידאו.", de: "Eine Person restauriert alte Fotos, eine andere baut Collagen - gern zusammen im Videocall mit bulgarischer Musik im Hintergrund.", en: "One restores old photos, another builds collages, and you can edit together on a video call with Bulgarian music playing." } },
      { id: 'cover', badge: 'noheb', links: ['main'],
        t: { he: 'עיצוב הכריכה', de: 'Cover und Look', en: 'Cover and look' },
        d: { he: 'בוחרים את פלטת הצבעים ואת הסגנון הגרפי של הספר, למשל ב-Canva.',
             de: 'Farben und grafischen Stil des Buchs aussuchen, zum Beispiel mit Canva.',
             en: 'Choose the colours and graphic style of the book, for example in Canva.' },
        ex: { he: 'למשל: פלטת הצבעים', de: 'z. B. die Farbpalette', en: 'e.g. the colour palette' },
        tip: { he: "כל אחד מציע סקיצה אחת, ובסוף כל המשפחה מצביעה על האהובה.", de: "Alle machen einen Entwurf, und am Ende stimmt die ganze Familie über ihren Favoriten ab.", en: "Everyone sketches one option, then the whole family votes for a favourite." } }
    ]
  },
  {
    num: 2,
    t: { he: 'מתכונים', de: 'Rezepte', en: 'Recipes' },
    sub: {
      he: 'הלב של הספר: מהמחברת של סבתא לדפים מסודרים שכל אחד יוכל לבשל מהם.',
      de: 'Das Herzstück des Buchs: Aus Omas Heft werden Seiten, nach denen alle kochen können.',
      en: "The heart of the book: turning Grandma's notebook into pages anyone can cook from."
    },
    tasks: [
      { id: 'notebook', badge: null, links: ['notebook', 'example'],
        t: { he: 'פענוח המחברת', de: 'Omas Heft entziffern', en: 'Deciphering the notebook' },
        d: { he: 'כל אחד לוקח 5-10 עמודים מהמחברת הסרוקה, מפענח את כתב היד ומקליד בפורמט אחיד: מצרכים לחוד ואופן הכנה לחוד. כדאי להציץ קודם בדוגמה.',
             de: 'Jede und jeder nimmt sich 5-10 Seiten aus dem eingescannten Heft vor, entziffert die Handschrift und tippt die Rezepte einheitlich ab: Zutaten und Zubereitung jeweils getrennt. Ein kurzer Blick ins Beispiel hilft.',
             en: 'Take 5-10 pages of the scanned notebook, decipher the handwriting and type the recipes up in one shared format, with ingredients and method listed separately. The example shows how.' },
        ex: { he: 'למשל: עמודים 11-20', de: 'z. B. Seiten 11-20', en: 'e.g. pages 11-20' },
        tip: { he: "כל אחד לוקח 5-10 עמודים, וכשמילה לא ברורה שואלים את סבתא - בדרך כלל מגיע איתה גם סיפור.", de: "Jede Person nimmt 5-10 Seiten, und wenn ein Wort unleserlich ist, einfach Oma fragen - meistens gibt es gleich eine Geschichte dazu.", en: "Take 5-10 pages each, and when a word won't give up its secret, ask Grandma - it usually comes with a story." } },
      { id: 'detective', badge: null, links: ['mustadd', 'example'],
        t: { he: 'בלשות קולינרית', de: 'Kulinarische Spurensuche', en: 'Culinary detective work' },
        d: { he: 'יש מנות שסבתא מכינה לפי העין, והן לא כתובות באף מחברת. מתקשרים לסבתא (או להורים), שואלים איך מכינים, ומתרגמים את זה לכמויות ברורות.',
             de: 'Manche Gerichte kocht Oma nach Gefühl, und sie stehen in keinem Heft. Einfach Oma (oder die Eltern) anrufen, nachfragen und daraus klare Mengenangaben machen.',
             en: 'Some of Grandma\'s dishes live only in her head. Give her (or the parents) a call, ask how she makes them, and turn "a pinch of this" into clear amounts.' },
        ex: { he: 'למשל: 5 המנות הראשונות ברשימה', de: 'z. B. die ersten 5 Gerichte auf der Liste', en: 'e.g. the first 5 dishes on the list' },
        tip: { he: "מתחלקים ברשימת המנות, ומבשלים עם סבתא (בבית או בווידאו) כשהמשקל וכוס המדידה בהישג יד.", de: "Die Liste der Gerichte aufteilen und mit Oma zusammen kochen, vor Ort oder per Video - Waage und Messbecher griffbereit.", en: "Split the list of dishes, then cook alongside Grandma, in person or on video, with a scale and measuring cup at hand." } },
      { id: 'qa', badge: null, links: ['example', 'main'],
        t: { he: 'בקרת איכות', de: 'Gegenlesen', en: 'Recipe check' },
        d: { he: 'קוראים את המתכונים המוקלדים ומוודאים שלא נשמטו בטעות "כפית מלח" או שלב חשוב.',
             de: 'Die abgetippten Rezepte in Ruhe durchlesen und schauen, dass kein Teelöffel Salz und kein wichtiger Schritt fehlt.',
             en: 'Read through the typed recipes and make sure no teaspoon of salt or important step slipped through the cracks.' },
        ex: { he: 'למשל: עמודים 1-30', de: 'z. B. Seiten 1-30', en: 'e.g. pages 1-30' },
        tip: { he: "מחלקים לפי טווחי עמודים, והמבחן האמיתי: מבשלים מתכון אחד בדיוק כמו שהוא כתוב.", de: "Nach Seitenbereichen aufteilen - und der echte Test: ein Rezept genau so nachkochen, wie es dasteht.", en: "Split by page range - and the real test: cook one recipe exactly as written." } }
    ]
  },
  {
    num: 3,
    t: { he: 'סיפורים וזיכרונות', de: 'Geschichten und Erinnerungen', en: 'Stories and memories' },
    sub: {
      he: 'כל מה שמסביב לאוכל: הסיפורים, המילים והרגעים המשותפים.',
      de: 'Alles rund ums Essen: die Geschichten, die Worte und die gemeinsamen Momente.',
      en: "Everything around the food: the stories, the words and the moments we've shared."
    },
    tasks: [
      { id: 'heritage', badge: null, links: ['main'],
        t: { he: 'השורשים הבולגריים', de: 'Bulgarische Wurzeln', en: 'Bulgarian roots' },
        d: { he: 'מחקר קצר על המאכלים הבולגריים של סבתא: מאיפה הם הגיעו ואיך התפתחו. אפשר לכתוב באנגלית או בגרמנית, ומישהו אחר יתרגם לעברית.',
             de: 'Ein bisschen Recherche zu Omas bulgarischen Gerichten: Woher kommen sie, und wie haben sie sich entwickelt? Gern auf Deutsch oder Englisch, die hebräische Übersetzung übernimmt jemand anderes.',
             en: "A little research into Grandma's Bulgarian dishes: where they come from and how they've changed over time. Write in English or German, and someone else will take care of the Hebrew translation." },
        ex: { he: 'למשל: 3 מנות לבחירתך', de: 'z. B. drei Gerichte meiner Wahl', en: 'e.g. three dishes of my choice' },
        tip: { he: "כל אחד בוחר 2-3 מנות, ושואל גם את סבתא איך קראו להן בבית.", de: "Jede Person sucht sich 2-3 Gerichte aus und fragt Oma, wie sie zu Hause genannt wurden.", en: "Each person picks 2-3 dishes and asks Grandma what they were called at home." } },
      { id: 'quotes', badge: null, links: ['main'],
        t: { he: 'המשפטים של סבתא', de: 'Omas Sprüche', en: "Grandma's sayings" },
        d: { he: 'פותחים קובץ חדש בתיקייה ואוספים בו את המשפטים והביטויים שסבתא תמיד אומרת.',
             de: 'Eine neue Datei im Ordner anlegen und darin Omas typische Sätze und Redewendungen sammeln.',
             en: 'Start a new file in the folder and gather the little phrases and sayings Grandma always comes out with.' },
        ex: { he: 'למשל: פתיחת הקובץ', de: 'z. B. die Datei anlegen', en: 'e.g. starting the file' },
        tip: { he: "כולם מוסיפים לאותו קובץ בכל פעם שהם שומעים משפט של סבתא, ומישהו אחד מסדר בסוף.", de: "Alle ergänzen dieselbe Datei, sobald sie einen Oma-Spruch hören, und am Ende bringt eine Person Ordnung hinein.", en: "Everyone adds to the same file whenever they hear a classic Grandma line, and one person tidies it up at the end." } },
      { id: 'memories', badge: 'all', all: true, links: ['main'],
        t: { he: 'זיכרונות מהמטבח', de: 'Küchenerinnerungen', en: 'Kitchen memories' },
        d: { he: 'כל אחד כותב פסקה קצרה על זיכרון מסבתא או מהאוכל שלה. אפשר לכתוב בשפת האם, והמקור יודפס בספר לצד התרגום לעברית.',
             de: 'Jede und jeder schreibt ein paar Zeilen über eine Erinnerung an Oma oder ihr Essen, gern in der eigenen Muttersprache. Im Buch steht das Original dann neben der hebräischen Übersetzung.',
             en: 'Everyone writes a few lines about a favourite memory of Grandma or her cooking, in whatever language feels most natural. The book will print the original alongside the Hebrew translation.' },
        ex: { he: 'למשל: איסוף הזיכרונות מזלצבורג', de: 'z. B. die Erinnerungen aus Salzburg sammeln', en: 'e.g. collecting the Salzburg memories' },
        tip: { he: "כל אחד כותב זיכרון אחד משלו, ומי שמעדיף לדבר יכול להקליט הודעה קולית שמישהו יקליד.", de: "Jede Person schreibt eine eigene Erinnerung auf - wer lieber erzählt, schickt eine Sprachnachricht, und jemand tippt sie ab.", en: "Everyone writes one memory of their own - if you'd rather talk, record a voice note and someone will type it up." } },
      { id: 'interview', badge: null, links: ['main'],
        t: { he: 'שיחה עם סבתא', de: 'Gespräch mit Oma', en: 'A chat with Grandma' },
        d: { he: 'יושבים עם סבתא לכוס קפה או ויטמינצ\'יק, בשיחת וידאו או בטלפון, ומתעדים את הסיפורים שלה: על הילדות, על אמא שלה, ומאיפה הגיעו המתכונים למשפחה.',
             de: 'Bei einer Tasse Kaffee oder einem Vitaminchik, per Videoanruf oder am Telefon mit Oma plaudern und ihre Geschichten festhalten: von ihrer Kindheit, von ihrer Mutter und davon, wie die Rezepte in die Familie kamen.',
             en: 'Sit down with Grandma over coffee or a Vitaminchik, on a video call or on the phone, and record her stories: her childhood, her mother, and how the recipes found their way into our family.' },
        ex: { he: 'למשל: סיפורי הילדות', de: 'z. B. Geschichten aus ihrer Kindheit', en: 'e.g. her childhood stories' },
        tip: { he: "מחלקים לפי נושאים (ילדות, אמא שלה, המתכונים) ומזכרת נחמדה יכולה להיות - להקליט את השיחה, כדי לשמור גם את הקול שלה.", de: "Nach Themen aufteilen (Kindheit, ihre Mutter, die Rezepte) und das Gespräch aufnehmen, damit auch ihre Stimme bleibt.", en: "Split by theme (childhood, her mother, the recipes) and record the conversation, so her voice is kept too." } },
      { id: 'blessings', badge: 'all', all: true, links: ['main'],
        t: { he: 'ברכות לסבתא', de: 'Glückwünsche für Oma', en: 'Birthday wishes' },
        d: { he: 'ברכה מכל אחד ואחת מאיתנו. בספר יהיו לכל אחד עמוד לברכה ועמוד לתמונות.',
             de: 'Ein Gruß von jeder und jedem von uns. Im Buch bekommt jede Person eine Seite für ihre Wünsche und eine für Fotos.',
             en: 'A message from each and every one of us. Everyone gets one page in the book for their wishes and one for photos.' },
        ex: { he: 'למשל: איסוף הברכות מכולם', de: 'z. B. alle Grüße einsammeln', en: "e.g. collecting everyone's wishes" },
        tip: { he: "כל אחד כותב ברכה משלו ובוחר תמונה משותפת עם סבתא לעמוד שלו.", de: "Alle schreiben ihren eigenen Gruß und suchen ein gemeinsames Foto mit Oma für ihre Seite aus.", en: "Everyone writes their own message and picks a photo with Grandma for their page." } }
    ]
  }
];
export const ALL_TASKS = PARTS.flatMap(p => p.tasks);
export const TASK_IDS = ALL_TASKS.map(t => t.id);
export const STATUSES = ['todo', 'doing', 'done'];
